[package]
name = "open-pond-protocol"
version = "0.1.0"
authors = ["William Greer <wgreer184@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.5.7"
serde = { version = "1.0", features = ["derive"] }
nom = "6.0.0"
byteorder = "1.3.4"
thiserror = "1.0.22"