[servicer]
address = "127.0.0.1:8081"
name = "Antelope"

[[peers]]
address = "127.0.0.1:8082"
name = "Bear"

[[peers]]
address = "127.0.0.1:8083"
name = "Cheetah"

[[apps]]
id = 1
requester = "127.0.0.1:9090"
servicer = "127.0.0.1:9091"
name = "Akron"