[settings]
requester_write = 9090
requester_read = 9091
servicer = 9092
servicer_manager = 9093

[local]
address = "127.0.0.1:8081"
name = "Antelope"

[[peers]]
address = "127.0.0.1:8082"
name = "Bear"

[[peers]]
address = "127.0.0.1:8083"
name = "Cheetah"

[[apps]]
id = 0
name = "Akron"