[package]
name = "open-pond-api"
version = "0.1.0"
authors = ["William Greer <wgreer184@gmail.com>"]
edition = "2018"

[dependencies]
open-pond-protocol = { path = "../open-pond-protocol", version = "0.1.0"}
thiserror = "1.0.22"
byteorder = "1.3.4"
base64 = "0.13.0"